FROM python:3.9-slim-buster

RUN mkdir -p /app

WORKDIR /app

RUN mkdir -p /postgres_data

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat gcc postgresql \
    && apt-get clean

RUN apt-get update &&\
    apt-get install -y binutils libproj-dev gdal-bin python-gdal python3-gdal
RUN pip3 install --upgrade pip

COPY Pipfile /app/Pipfile
COPY Pipfile.lock /app/Pipfile.lock
RUN pip3 install pipenv && pipenv install --dev --system --deploy

RUN pipenv install --dev --system --deploy

COPY . /app
